### ISSUE TITLE
About student checkpoint

### ISSUE THREAD

**Issue by notou10** [hunto/DIST_KD#1]
Hi guys, thanks for your work!

What I wanna do is to do an experiment with a distillated student, but I don't have enough gpu to conduct distillation with imagenet dataset.

Could you give me the checkpoint(ImageNet trained) of ResNet18 that is distilled from teacher tv_ResNet34?

Again, really thanks from your great work!

**Comment by hunto** [comment]
Hi notou10,

Thanks for your interests on our work.

Since I'm temporally leaving my previous company where stores the checkpoints in the server, it needs 1~2 weeks for me to get and upload the checkpoints. 

You can track this issue, and once the checkpoints are uploaded, you will receive a notification.

Thanks again for your issue.

**Comment by notou10** [comment]
Thanks, I'll keep an eye on this issue!

Thank you for your good research.

**Comment by hunto** [comment]
Hi notou10,

The original `72.07` checkpoint was lost, but we have re-implemented a model with `72.05%` ACC, and the checkpoint has been uploaded to https://drive.google.com/file/d/1_nzcAwxZApLU496iypsdeNhXYzPA4ZF4/view?usp=sharing 

Hope this checkpoint can help you. We are collecting the checkpoints for other models, and they will be uploaded and updated in `README.md` soon.

**Comment by notou10** [comment]
thanks a lot. Wish you all the best!
